import { cn } from "@/lib/utils";
import type { Metadata } from "next";
import { DM_Sans, JetBrains_Mono } from "next/font/google";
import { FC } from "react";
import "./globals.css";

const jetBrainsMono = JetBrains_Mono({ subsets: ["latin"] });
const dmSans = DM_Sans({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Message Moment",
  description: "Generated by Sunnah It. Powered by Baitul Hikmah Team",
};

const RootLayout: FC<IChildren> = ({ children }) => (
  <html lang="en">
    <body className={cn(jetBrainsMono.className, dmSans.className)}>
      {children}
    </body>
  </html>
);

export default RootLayout;
